### ISSUE TITLE
Request for Updates on SimpleShot Code for ESC-50 Dataset

### ISSUE THREAD

**Issue by ohTW** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#14]
Hello researcher!
I am a university student currently studying few-shot learning. I was wondering if you will still update the sample code? I'm very interested in your implementation of SimpleShot on the ESC-50 dataset, but I'm having trouble getting started.
Looking forward to your response, and I wish you a wonderful day!

**Comment by CHeggan** [comment]
Hi there, 

Thank you for the warm wishes, I wish you the same. This is still in my plans yes, I have just become busy with other projects. I will have a look at uploading at least a rough version of this example code in the following week or two!

Cheers,
Calum

**Comment by CHeggan** [comment]
Hi there, 

I have uploaded a SimpleShot with ESC example. Due to time restrictions it is less clean and polished compared to the other examples but should hopefully give you an idea of implementation.

Best,
Calum
