### ISSUE TITLE
How to implement Meta-Curvature

### ISSUE THREAD

**Issue by nick89216kuo** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#20]
Hello researcher!
I was wondering if your Meta-Curvature is also implemented using the learn2learn library, similar to the sample code for MAML.

I am currently trying to reproduce Meta-Curvature using the following code:
gbml = l2l.algorithms.GBML(model,transform=MetaCurvatureTransform,lr=params['hyper']['inner_lr'],adapt_transform=False,first_order=True)

However, the results I'm getting are not satisfactory.

**Comment by CHeggan** [comment]
Hi there, 

Yes we used the learn2learn implementation. That code generally looks okay. Here is the snipper from the code used to produce these results. 

```
    # Start with first order with option to change later
    meta_curve = l2l.algorithms.GBML(
                module=model,
                transform=l2l.optim.MetaCurvatureTransform,
                lr=params['hyper']['inner_lr'],
                adapt_transform=False,
                first_order=True, # has both 1st and 2nd order versions
    ).to(device, dtype=torch.double)


    meta_opt = optim.Adam(meta_curve.parameters(), lr=params['hyper']['meta_start_lr'])
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer=meta_opt,
                                        mode='min',
                                        patience=params['hyper']['patience'],
                                        factor=params['hyper']['factor'],
                                        min_lr=params['hyper']['min_meta_lr'])


    loss_fn = nn.CrossEntropyLoss().to(device)
```

Note that we also use scheduling etc. Please also find attached some hyperparameters used to obtain teh results in the paper:

![image](https://github.com/CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark/assets/38021095/3d8da3e8-22c6-4055-8f48-4650717c95a4)

I don't have these in an easily sharable format for all datasets at the moment, but these should give you a starting point.

Best,
Calum

**Comment by nick89216kuo** [comment]
Thank you for the information you provided.

Wishing you a wonderful day.
