### ISSUE TITLE
I would like to run experiements using voxceleb1 dataset, but it seems like not publicly available now. Could you provide the dataset?

### ISSUE THREAD

**Issue by Xiang47** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#21]

**Comment by CHeggan** [comment]
Hi there, 

Unfortunately, because VoxCeleb contains copyrighted material, I cannot readily pass out/host the dataset legally.
It looks like the download files may still be active here however: [VoxCeleb](https://mm.kaist.ac.kr/datasets/voxceleb/ )
