### ISSUE TITLE
to_spec.py IndentationError

### ISSUE THREAD

**Issue by nick89216kuo** [CHeggan/MetaAudio-A-Few-Shot-Audio-Classification-Benchmark#7]
Hello respected researcher! I encountered the following issue while running to_spec.py, and after trying to troubleshoot the problem, I found that both .wav and .npy files are being generated in the same folder (Sorted). Can you please let me know if there's something I did wrong?

Traceback (most recent call last):
  File "full_stack_ESC.py", line 27, in <module>
    from to_spec import main as to_spec_main
  File "/home/mitlab/kuo/ESC-50-master/to_spec.py", line 45
    if audio_data.shape[0] < 160000:
                                   ^
IndentationError: unindent does not match any outer indentation level

**Comment by CHeggan** [comment]
Hi there, I am not immediately sure how both .wav and .npy files are ending up in the same folder. For now however, I have updated the to_spec.py file and hopefully dealt with the indentation issue. Let me know if this helps or solves the issue!

Cheers,
Calum

**Comment by CHeggan** [comment]
Hi there, 

So the ACDNets was legacy code. It has now been removed from the ESC MAML example.

For the second issue related to key errors, this occurs when the path set for data isnt correct or has some issue with string formatting. This can be checked by looking at the data path. If I remember correctly, the code in this repo is designed around windows, meaning that the issue could be the use of separators '\' and '\\'.  

Cheers,
Calum

**Comment by nick89216kuo** [comment]
Thank you for taking the time to help me with my issues. I will try to resolve the problems with the operating system. Wishing you a wonderful day!

**Comment by nick89216kuo** [comment]
Hello researcher! I'm happy to report that I've resolved the file path issue. However, I've encountered another error shortly after. This error has been previously discussed by someone, but even after reviewing the issues, I still don't quite understand the root cause of the problem and how to address it. Could I trouble you for your assistance? Below is the error report.

Traceback (most recent call last):
  File "BaseLooper.py", line 107, in <module>
    pre, post, loss, post_std = single_run_main(params=params, 
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/MAML_Main.py", line 45, in main
    setup = DatasetSetup(params=params,
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/SetupClass.py", line 79, in __init__
    stats = gen_training_stats(data_path=data_path, 
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/dataset_stuff.py", line 133, in gen_training_stats
    stats_class.update(x)
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/stat_recorder_class.py", line 23, in update
    self.mean = data.mean(dim=self.red_dims, keepdim=True)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

**Comment by CHeggan** [comment]
Hi there, this error likely occurs due to a batching issue. The stat recorder class relies on an input of shape [batch_size, time dimension, nmels]. When data is being passed through here, it likely doesn't contain the batch dimension, this can be verified by printing out the sample immediately before this error triggers.

If this is in fact the case, you have two options:
 - Unsqueeze the sample in the batch dimension immediately before this error, i.e sample = sample.unsqueeze(0)
 - Track the source of why the class and its mean function isn't receiving a batch set of samples, this could be due to a config difference or something like this

Cheers,
Calum

**Comment by nick89216kuo** [comment]
Researcher, hello again! I apologize for bothering you once more. In order to address the previous issue, I used the method data = data.unsqueeze(0). However, I have encountered the following problem, and I'm not sure if it's related to the batch size.

Traceback (most recent call last):
  File "BaseLooper.py", line 110, in <module>
    pre, post, loss, post_std = single_run_main(params=params, 
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/MAML_Main.py", line 45, in main
    setup = DatasetSetup(params=params,
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/SetupClass.py", line 79, in __init__
    stats = gen_training_stats(data_path=data_path, 
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/dataset_stuff.py", line 133, in gen_training_stats
    stats_class.update(x)
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/dataset_/stat_recorder_class.py", line 30, in update
    raise ValueError('Data dims do not match previous observations.')
ValueError: Data dims do not match previous observations.

**Comment by CHeggan** [comment]
Hi there, 

If this didn't solve the problem, I would hazard a guess that the issue is a mismatch between the type of data you are using (i.e. variable_spec, spec etc) and what the code thinks you are using. It is worth looking at changing this in the config depending on what set you are using. For example, if you are using ESC-50, If i remember correctly, you should be using spec as the data_type not variable_spec.

If this doesn't work, please provide the type of data type used in config as well as what the dimensionality of the input tensor before this error triggers.

Best,
Calum

**Comment by nick89216kuo** [comment]
Hello researcher! Despite changing the data_type to "spec," it still doesn't work. Here are the tensor sizes after using data = data.unsqueeze(0):

torch.Size([1, 500, 128, 157])
torch.Size([1, 500, 128, 157])
torch.Size([1, 400, 128, 157])

**Comment by nick89216kuo** [comment]
Hello researcher! I have successfully resolved this issue, but I have encountered a new problem. The error message is as follows: 
Traceback (most recent call last):
  File "BaseLooper.py", line 108, in <module>
    pre, post, loss, post_std = single_run_main(params=params, 
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/MAML_Main.py", line 144, in main
    pre, post, loss, post_std = fit(
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/fit.py", line 115, in fit
    val_df = update_csv(val_path, val_df, val_data)
  File "/home/mitlab/kuo/MetaAudio-A-Few-Shot-Audio/Examples/MAML_ESC/utils.py", line 31, in update_csv
    new_df = df.append(new_data, ignore_index=True)
  File "/home/mitlab/anaconda3/envs/metaaudio/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
I'm really glad to have your help. Thank you.

**Comment by CHeggan** [comment]
Hi there, this issue is likely die to the depreciation of the append function in newer versions of pandas. If you reference your version with that in the environment file, you can ensure you have the same version (which should contain append functionality)

Best,
Calum

**Comment by nick89216kuo** [comment]
Hello researcher! I successfully resolved the issue by rewriting the code using concat. I'm truly thankful for your continuous assistance.

Lastly, I'd like to ask about any tips regarding the implementation of FO-Meta-Curvature. I tried using MetaCurvatureTransform from learn2learn.optim.transforms, but it only resulted in a 72% accuracy.

**Comment by CHeggan** [comment]
Hi there, 

So my first guess as to this issue would be hyperparameters within the inner update loop. We found that the inner loop optimisation is incredibly important, i.e. how many inner steps are used with what learning rate.

Some other things to check:
 - The ESC split is the same
 - Environment is exactly the same (small differences here can cause initialisation or optimisation issues)
 - Check hyperparams used

Best,
Calum
